steemit/devportal-tutorials-py

tutorials/08_get_account_replies/README.md, tutorials/08_get_account_replies/index.py, tutorials/08_get_account_replies/requirements.txt
=> 26 get replies made on accounts content

tutorials/09_get_account_comments/README.md, tutorials/09_get_account_comments/index.py, tutorials/09_get_account_comments/requirements.txt
=> PY-T: Get comments made by account

tutorials/00_getting_started/README.md
=> this link will be better handled by DP rake tasks #44

tutorials/10_submit_post/README.md, tutorials/10_submit_post/index.py, tutorials/10_submit_post/requirements.txt
=> #24 submit post tut

tutorials/11_reblog_post/README.md, tutorials/11_reblog_post/index.py, tutorials/11_reblog_post/requirements.txt
=> PYT reblog post

tutorials/13_account_reputation/README.md, tutorials/13_account_reputation/index.py, tutorials/13_account_reputation/requirements.txt
=> PYT: account reputation

README.md, tutorials/00_getting_started/README.md, tutorials/01_get_posts/README.md, tutorials/02_get_post_details/README.md, tutorials/03_get_voters_list/README.md, tutorials/04_get_post_replies/README.md, tutorials/08_get_account_replies/README.md, tutorials/09_get_account_comments/README.md, tutorials/10_submit_post/README.md, tutorials/11_reblog_post/README.md, tutorials/12_using_keys_securely/README.md, tutorials/13_account_reputation/README.md
=> Fix repetitive boilerplate text, and update tutorials list, linking

tutorials/14_submit_comment_reply/README.md, tutorials/14_submit_comment_reply/index.py, tutorials/14_submit_comment_reply/requirements.txt
=> submit comment/reply tutorial (#23)

tutorials/15_get_follower_and_following_list/README.md, tutorials/15_get_follower_and_following_list/index.py, tutorials/15_get_follower_and_following_list/requirements.txt
=> 18 get follower and following list

tutorials/17_search_accounts_and_tags/README.md, tutorials/17_search_accounts_and_tags/index.py, tutorials/17_search_accounts_and_tags/requirements.txt
=> search accounts and tags tutorial #20

tutorials/16_follow_another_user/README.md, tutorials/16_follow_another_user/index.py, tutorials/16_follow_another_user/requirements.txt
=> 17 follow another user

tutorials/18_vote_on_content/README.md, tutorials/18_vote_on_content/index.py, tutorials/18_vote_on_content/requirements.txt
=> 19 vote on content

tutorials/21_transfer_STEEM_and_SBD/README.md, tutorials/21_transfer_STEEM_and_SBD/index.py, tutorials/21_transfer_STEEM_and_SBD/requirements.txt
=> transfer STEEM and SBD tutorial

tutorials/29_get_delegations_by_user/README.md, tutorials/29_get_delegations_by_user/index.py, tutorials/29_get_delegations_by_user/requirements.txt
=> PY-T: get delegations by user #07

tutorials/23_claim_rewards/README.md, tutorials/23_claim_rewards/index.py, tutorials/23_claim_rewards/requirements.txt
=> 15 claim rewards

tutorials/25_power_down_steem/README.md, tutorials/25_power_down_steem/index.py, tutorials/25_power_down_steem/requirements.txt
=> PY-T: Power down STEEM #10

tutorials/31_grant_active_permission/README.md, tutorials/31_grant_active_permission/index.py, tutorials/31_grant_active_permission/requirements.txt
=> PY-T: Grant active permission to another account #04

tutorials/27_delegate_power/README.md, tutorials/27_delegate_power/index.py, tutorials/27_delegate_power/requirements.txt
=> PY-T: Delegate STEEM POWER #8

tutorials/30_grant_posting_permission/README.md, tutorials/30_grant_posting_permission/index.py, tutorials/30_grant_posting_permission/requirements.txt
=> PY-T: Grant posting permission to another account #5

tutorials/22_witness_listing_and_voting/README.md, tutorials/22_witness_listing_and_voting/index.py, tutorials/22_witness_listing_and_voting/requirements.txt
=> PY-T: Witness listing/voting/unvoting #9

README.md, tutorials/00_getting_started/README.md
=> 72 broken link on getting started page

tutorials/18_follow_a_user/README.md
=> Fix anchor link for follow status

README.md, tutorials/33_password_key_change/README.md, tutorials/33_password_key_change/index.py, tutorials/33_password_key_change/requirements.txt
=> Tutorial Password Key Change

README.md, tutorials/13_stream_blockchain_transactions/README.md, tutorials/13_stream_blockchain_transactions/index.py, tutorials/13_stream_blockchain_transactions/requirements.txt
=> 06 stream operations

README.md
=> Fix a link to 001_using_keys_securely
